apiVersion: v1
kind: Service
metadata:
  name: gateway
  labels:
    version: dev
    product: gateway
spec:
  selector:
    app: gateway
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http


---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: gateway
          imagePullPolicy: Never
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
          ports:
            - containerPort: 80
              protocol: TCP