apiVersion: v1
kind: Service
metadata:
  name: diary-client
spec:
  type: LoadBalancer
  selector:
    app: web
  ports:
    - port: 81
      targetPort: 80
      protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: learningdiaryapi
spec:
  type: LoadBalancer
  selector:
    app: learningdiaryapi
  ports:
    - port: 82
      targetPort: 80
      protocol: TCP

#---

#apiVersion: v1
#kind: Service
#metadata:
#  name: gateway
#spec:
#  type: LoadBalancer
#  selector:
#    app: gateway
#  ports:
#    - port: 81
#      targetPort: 80
#      protocol: TCP